name: result_to_grafbase
slug: result_to_grafbase
graphql:
  resource: hackweek_example
  operation: |-
    mutation create($input: ReportCreateInput!) {
      reportCreate(input: $input) {
        report {
          userid
          id
          content
          updatedAt
          createdAt
        }
      }
    }
  variables:
    input:
      content: "{{params.report_content}}"
      userid: "{{params.user_id}}"
  retryFailures: false
parameters:
  - name: User ID
    slug: user_id
    type: shorttext
    description: The ID of the user
  - name: Report content
    slug: report_content
    type: longtext
    description: The body of the batch run result we want to expose